#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import tarfile
import tempfile
from datetime import datetime, timezone
from pathlib import Path


SECRET_KEY_RE = re.compile(
    r"(token|secret|password|passphrase|api[_-]?key|private[_-]?key|bot[_-]?token|dsn|webhook|bearer|auth)",
    re.IGNORECASE,
)
PLACEHOLDER_TEMPLATE = "__SECRET_{name}__"

REPO_EXCLUDES = {
    ".git",
    "node_modules",
    "dist",
    "coverage",
    ".turbo",
}

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Export sanitized OpenClaw agent code/config bundle plus separate secrets env."
    )
    parser.add_argument(
        "--repo-root",
        default=None,
        help="OpenClaw repo root. Defaults to this script's repo.",
    )
    parser.add_argument(
        "--config-dir",
        default=None,
        help="OpenClaw config dir. Defaults to $OPENCLAW_CONFIG_DIR or ~/.openclaw.",
    )
    parser.add_argument(
        "--output-dir",
        default=None,
        help="Output directory for bundle folder, archive, and secrets env. Defaults to current directory.",
    )
    parser.add_argument(
        "--bundle-name",
        default=None,
        help="Bundle name prefix. Defaults to openclaw-agent-bundle-YYYYmmdd-HHMMSS.",
    )
    parser.add_argument(
        "--docker-container",
        default=None,
        help="Optional Docker container name to read config from via docker cp.",
    )
    parser.add_argument(
        "--docker-config-dir",
        default="/home/node/.openclaw",
        help="Config directory inside Docker container when --docker-container is used.",
    )
    parser.add_argument(
        "--repo-baseline-dir",
        default=None,
        help="Optional unpacked baseline source tree. If provided, export only repo files changed relative to this tree.",
    )
    return parser.parse_args()


def shell_quote(value: str) -> str:
    return "'" + value.replace("'", "'\"'\"'") + "'"


def to_env_name(parts: list[str]) -> str:
    raw = "_".join(parts).upper()
    raw = re.sub(r"[^A-Z0-9]+", "_", raw)
    raw = re.sub(r"_+", "_", raw).strip("_")
    if not raw.startswith("SECRET_"):
        raw = f"SECRET_{raw}"
    return raw


class SecretStore:
    def __init__(self) -> None:
        self.values: dict[str, str] = {}
        self.reverse: dict[str, str] = {}

    def placeholder(self, env_name: str, value: str) -> str:
        if not value:
            return value
        existing = self.reverse.get(value)
        if existing:
            return PLACEHOLDER_TEMPLATE.format(name=existing)
        self.values[env_name] = value
        self.reverse[value] = env_name
        return PLACEHOLDER_TEMPLATE.format(name=env_name)

    def write_env(self, path: Path) -> None:
        lines = [
            "# Generated by agent_bundle_export.py",
            "# Keep this file outside the archive.",
            "",
        ]
        for name in sorted(self.values):
            lines.append(f"{name}={shell_quote(self.values[name])}")
        lines.append("")
        path.write_text("\n".join(lines), encoding="utf-8")


def should_treat_as_text(path: Path) -> bool:
    return path.suffix.lower() in {
        ".json",
        ".jsonl",
        ".md",
        ".ts",
        ".js",
        ".mjs",
        ".cjs",
        ".yml",
        ".yaml",
        ".env",
        ".txt",
        ".sh",
        ".py",
    } or path.name in {".env", "Dockerfile"}


def is_secret_key(key: str) -> bool:
    return bool(SECRET_KEY_RE.search(key))


def sanitize_json_value(
    obj,
    store: SecretStore,
    path_parts: list[str],
):
    if isinstance(obj, dict):
        result = {}
        for key, value in obj.items():
            child_parts = path_parts + [key]
            if isinstance(value, str) and value and is_secret_key(key):
                env_name = to_env_name(child_parts)
                result[key] = store.placeholder(env_name, value)
            else:
                result[key] = sanitize_json_value(value, store, child_parts)
        return result
    if isinstance(obj, list):
        return [sanitize_json_value(v, store, path_parts + [str(i)]) for i, v in enumerate(obj)]
    return obj


LINE_SECRET_RE = re.compile(
    r'^(\s*(?:export\s+)?)([A-Za-z_][A-Za-z0-9_]*(?:TOKEN|SECRET|PASSWORD|PASS|API_KEY|BOT_TOKEN|DSN|PRIVATE_KEY|AUTH)[A-Za-z0-9_]*)\s*=\s*(.+?)\s*$'
)
JSON_INLINE_SECRET_RE = re.compile(
    r'("(?P<key>[^"]*(?:token|secret|password|api[_-]?key|bot[_-]?token|private[_-]?key|dsn|auth)[^"]*)"\s*:\s*)"(?P<value>[^"]+)"',
    re.IGNORECASE,
)


def sanitize_text_content(text: str, store: SecretStore, rel_path: Path) -> str:
    if rel_path.suffix.lower() == ".json":
        try:
            parsed = json.loads(text)
        except json.JSONDecodeError:
            parsed = None
        if parsed is not None:
            sanitized = sanitize_json_value(parsed, store, [*rel_path.parts])
            return json.dumps(sanitized, ensure_ascii=False, indent=2) + "\n"

    lines: list[str] = []
    for line_no, line in enumerate(text.splitlines(), start=1):
        line_match = LINE_SECRET_RE.match(line)
        if line_match:
            prefix, key, raw_value = line_match.groups()
            value = raw_value.strip().strip('"').strip("'")
            env_name = to_env_name([*rel_path.parts, key])
            placeholder = store.placeholder(env_name, value)
            lines.append(f"{prefix}{key}={placeholder}")
            continue
        lines.append(line)
    sanitized = "\n".join(lines)
    if text.endswith("\n"):
        sanitized += "\n"

    def repl(match: re.Match[str]) -> str:
        key = match.group("key")
        value = match.group("value")
        env_name = to_env_name([*rel_path.parts, key])
        placeholder = store.placeholder(env_name, value)
        return f'{match.group(1)}"{placeholder}"'

    return JSON_INLINE_SECRET_RE.sub(repl, sanitized)


def copy_and_sanitize_tree(
    source_root: Path,
    relative_path: Path,
    dest_root: Path,
    store: SecretStore,
    sanitize: bool = True,
) -> None:
    src = source_root / relative_path
    dst = dest_root / relative_path
    if src.is_dir():
        dst.mkdir(parents=True, exist_ok=True)
        for child in sorted(src.iterdir()):
            copy_and_sanitize_tree(
                source_root,
                relative_path / child.name,
                dest_root,
                store,
                sanitize=sanitize,
            )
        return
    if src.is_symlink():
        resolved = src.resolve(strict=True)
        if resolved.is_dir():
            raise SystemExit(f"Directory symlinks are not supported: {src}")
        src = resolved
    dst.parent.mkdir(parents=True, exist_ok=True)
    if sanitize and should_treat_as_text(src):
        content = src.read_text(encoding="utf-8")
        dst.write_text(sanitize_text_content(content, store, relative_path), encoding="utf-8")
    else:
        shutil.copy2(src, dst)


def write_import_script(template_path: Path, target_path: Path) -> None:
    target_path.write_text(template_path.read_text(encoding="utf-8"), encoding="utf-8")
    target_path.chmod(0o755)


def write_readme(target_path: Path) -> None:
    target_path.write_text(
        "\n".join(
            [
                "# OpenClaw Agent Bundle",
                "",
                "This archive contains:",
                "- `bundle/` - sanitized repo/config payload with placeholders instead of secrets",
                "- `import_bundle.py` - importer that restores placeholders from environment variables and syncs files into target locations",
                "",
                "Secrets are intentionally not stored in the archive.",
                "They are written separately by the exporter into a sibling file named `*.secrets.env`.",
                "",
                "## Import",
                "",
                "1. Extract the archive.",
                "2. Load secrets into the shell environment.",
                "3. Run the importer and point it at the target repo/config roots.",
                "",
                "Example:",
                "```bash",
                "tar -xzf openclaw-agent-bundle-*.tar.gz",
                "set -a",
                "source openclaw-agent-bundle-*.secrets.env",
                "set +a",
                "python3 import_bundle.py \\",
                "  --bundle-dir ./bundle \\",
                "  --repo-root /path/to/openclaw \\",
                "  --config-dir /path/to/.openclaw",
                "```",
                "",
                "## Dry Run",
                "",
                "Use `--dry-run` first to preview what will be written:",
                "```bash",
                "python3 import_bundle.py \\",
                "  --bundle-dir ./bundle \\",
                "  --repo-root /path/to/openclaw \\",
                "  --config-dir /path/to/.openclaw \\",
                "  --dry-run",
                "```",
                "",
                "If any required secret environment variables are missing, the importer exits with an error before syncing files.",
                "",
                "## Baseline Diff Mode",
                "",
                "If the original installation came from an archive instead of git, export can compare the current repo tree",
                "against an unpacked baseline source tree and include only changed repo files plus explicit removals.",
                "",
                "Example export:",
                "```bash",
                "python3 tools/agent_bundle_export.py \\",
                "  --repo-root /path/to/current/openclaw \\",
                "  --repo-baseline-dir /path/to/original-archive-source \\",
                "  --docker-container openclaw-openclaw-gateway-1 \\",
                "  --output-dir /path/to/output",
                "```",
                "",
                "Recommended restore flow:",
                "1. Download or clone a clean upstream repo.",
                "2. Load secrets from `*.secrets.env`.",
                "3. Run `import_bundle.py` to overlay only your repo changes and fully sync config.",
                "",
            ]
        )
        + "\n",
        encoding="utf-8",
    )


def materialize_config_source(args: argparse.Namespace, config_dir: Path) -> tuple[Path, tempfile.TemporaryDirectory[str] | None]:
    if args.docker_container:
        temp_dir = tempfile.TemporaryDirectory(prefix="agent-bundle-config-")
        staged_root = Path(temp_dir.name) / "config"
        staged_root.mkdir(parents=True, exist_ok=True)
        subprocess.run(
            [
                "docker",
                "cp",
                f"{args.docker_container}:{args.docker_config_dir}/.",
                str(staged_root),
            ],
            check=True,
        )
        return staged_root, temp_dir
    return config_dir, None


def build_manifest(
    repo_sync_files: list[str],
    repo_sync_dirs: list[str],
    repo_remove_paths: list[str],
    config_sync_files: list[str],
    config_sync_dirs: list[str],
    config_remove_paths: list[str],
    repo_root: Path,
    config_dir: Path,
) -> dict:
    return {
        "schema": 1,
        "created_at": datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z"),
        "repo_root_hint": str(repo_root),
        "config_dir_hint": str(config_dir),
        "repo_sync_files": repo_sync_files,
        "repo_sync_dirs": repo_sync_dirs,
        "repo_remove_paths": repo_remove_paths,
        "config_sync_files": config_sync_files,
        "config_sync_dirs": config_sync_dirs,
        "config_remove_paths": config_remove_paths,
    }


def file_bytes(path: Path) -> bytes:
    src = path
    if src.is_symlink():
        resolved = src.resolve(strict=True)
        if resolved.is_dir():
            raise SystemExit(f"Directory symlinks are not supported: {path}")
        src = resolved
    return src.read_bytes()


def collect_repo_paths(repo_root: Path, repo_sync_dirs: list[str], repo_sync_files: list[str]) -> set[Path]:
    collected: set[Path] = set()
    for rel in repo_sync_files:
        path = repo_root / rel
        if path.exists():
            collected.add(Path(rel))
    for rel_dir in repo_sync_dirs:
        root = repo_root / rel_dir
        for path in root.rglob("*"):
            if path.is_dir():
                continue
            collected.add(path.relative_to(repo_root))
    return collected


def build_repo_delta(
    repo_root: Path,
    baseline_root: Path,
    repo_sync_dirs: list[str],
    repo_sync_files: list[str],
) -> tuple[list[str], list[str], list[str]]:
    current_paths = collect_repo_paths(repo_root, repo_sync_dirs, repo_sync_files)
    baseline_paths = collect_repo_paths(baseline_root, repo_sync_dirs, repo_sync_files)

    changed: list[str] = []
    removed: list[str] = []

    for rel in sorted(current_paths):
        current_file = repo_root / rel
        baseline_file = baseline_root / rel
        if not baseline_file.exists():
            changed.append(rel.as_posix())
            continue
        if file_bytes(current_file) != file_bytes(baseline_file):
            changed.append(rel.as_posix())

    for rel in sorted(baseline_paths - current_paths):
        removed.append(rel.as_posix())

    return changed, [], removed


def main() -> int:
    args = parse_args()
    script_path = Path(__file__).resolve()
    repo_root = Path(args.repo_root or script_path.parents[1]).resolve()
    baseline_repo_root = Path(args.repo_baseline_dir).resolve() if args.repo_baseline_dir else None
    config_dir = Path(
        args.config_dir
        or os.environ.get("OPENCLAW_CONFIG_DIR")
        or (Path.home() / ".openclaw")
    ).resolve()
    output_dir = Path(args.output_dir or Path.cwd()).resolve()
    bundle_name = args.bundle_name or f"openclaw-agent-bundle-{datetime.now().strftime('%Y%m%d-%H%M%S')}"

    bundle_root = output_dir / bundle_name
    archive_path = output_dir / f"{bundle_name}.tar.gz"
    secrets_path = output_dir / f"{bundle_name}.secrets.env"
    if bundle_root.exists():
        shutil.rmtree(bundle_root)
    bundle_root.mkdir(parents=True, exist_ok=True)

    store = SecretStore()
    effective_config_dir, temp_config_dir = materialize_config_source(args, config_dir)
    try:
        repo_dest = bundle_root / "bundle" / "repo"
        config_dest = bundle_root / "bundle" / "config"
        repo_dest.mkdir(parents=True, exist_ok=True)
        config_dest.mkdir(parents=True, exist_ok=True)

        repo_base_dirs = ["src", "tools"]
        repo_base_files = ["docker-compose.yml", "package.json", "pnpm-lock.yaml", "tsconfig.json"]
        repo_base_files = [p for p in repo_base_files if (repo_root / p).exists()]
        repo_base_dirs = [p for p in repo_base_dirs if (repo_root / p).exists()]
        repo_remove_paths: list[str] = []
        if baseline_repo_root is not None:
            repo_sync_files, repo_sync_dirs, repo_remove_paths = build_repo_delta(
                repo_root,
                baseline_repo_root,
                repo_base_dirs,
                repo_base_files,
            )
        else:
            repo_sync_dirs = repo_base_dirs
            repo_sync_files = repo_base_files
        for rel in repo_sync_dirs:
            copy_and_sanitize_tree(repo_root, Path(rel), repo_dest, store, sanitize=False)
        for rel in repo_sync_files:
            copy_and_sanitize_tree(repo_root, Path(rel), repo_dest, store, sanitize=False)

        config_candidates = [
            "openclaw.json",
            "exec-approvals.json",
            "agents/clinic/agent/auth-profiles.json",
            "agents/clinic/agent/models.json",
            "agents/main/agent/auth.json",
            "agents/main/agent/auth-profiles.json",
            "agents/main/agent/models.json",
            "credentials/telegram-default-allowFrom.json",
            "credentials/telegram-pairing.json",
            "devices/paired.json",
            "devices/pending.json",
            "identity/device-auth.json",
            "identity/device.json",
            "extensions/fh-api/index.ts",
            "extensions/fh-api/openclaw.plugin.json",
            "skills/family-health-scheduler/SKILL.md",
            "workspace-clinic/AGENTS.md",
            "workspace-clinic/BOOTSTRAP.md",
            "workspace-clinic/HEARTBEAT.md",
            "workspace-clinic/IDENTITY.md",
            "workspace-clinic/SOUL.md",
            "workspace-clinic/TOOLS.md",
            "workspace-clinic/USER.md",
            "workspace-clinic/.openclaw/workspace-state.json",
        ]
        config_sync_files: list[str] = []
        config_sync_dirs: list[str] = []
        config_remove_paths: list[str] = []
        for rel in config_candidates:
            rel_path = Path(rel)
            src = effective_config_dir / rel_path
            if not src.exists():
                continue
            if src.is_dir():
                config_sync_dirs.append(rel)
            else:
                config_sync_files.append(rel)
            copy_and_sanitize_tree(effective_config_dir, rel_path, config_dest, store)

        manifest = build_manifest(
            repo_sync_files,
            repo_sync_dirs,
            repo_remove_paths,
            config_sync_files,
            config_sync_dirs,
            config_remove_paths,
            repo_root,
            config_dir,
        )
        manifest_path = bundle_root / "bundle" / "manifest.json"
        manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

        import_template = repo_root / "tools" / "agent_bundle_import.py"
        write_import_script(import_template, bundle_root / "import_bundle.py")
        write_readme(bundle_root / "README.md")
        store.write_env(secrets_path)

        with tarfile.open(archive_path, "w:gz") as tar:
            tar.add(bundle_root / "bundle", arcname="bundle")
            tar.add(bundle_root / "import_bundle.py", arcname="import_bundle.py")
            tar.add(bundle_root / "README.md", arcname="README.md")
    finally:
        if temp_config_dir is not None:
            temp_config_dir.cleanup()

    print(f"Bundle directory: {bundle_root}")
    print(f"Archive: {archive_path}")
    print(f"Secrets env: {secrets_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
